### ISSUE TITLE
Test data set

### ISSUE THREAD

**Issue by TT-mouse** [Yang-Shiyuan/ResInpainting#2]
作者你好，我在使用你给出的预训练模型进行测试时遇到了一个问题：请问在巴黎街景数据集上进行测试所使用的1000张图片是怎么设置的？
@Yang-Shiyuan

**Comment by cats-food** [comment]
你好，我记得官方psv数据集只有50张真值，我当时复用了这些图，每次复用都用不同比例的mask，所以可以得到多张不同的输入

**Comment by TT-mouse** [comment]
您所说的复用是直接把原有真值图片复制到1000张吗？然后分别在不同比例掩码下进行测试吗？

**Comment by cats-food** [comment]
是的，复制20份，然后每份对应不同比例掩码

**Comment by TT-mouse** [comment]
您的掩码是使用的10-30%，30-50%，50-70%，是在每个比例下都使用1000张进行测试吗？无规则掩码数据集的每个小比例都有2000张，在每个比例下的掩码是随机选取的吗？

**Comment by cats-food** [comment]
你好，我刚刚去翻了一下，结合我的回忆，实际上是这样的：
psv原始数据集其实只提供了100张测试样本，我个人将其额外复制了9份，共1000份。
掩码数据（小）：从nvidia mask数据集中0-0.1，0.1-0.2，0.2-0.3，0.3-0.4，0.4-0.5五种掩模区间各取100份，共500份
掩码数据（大）：0.5-0.6, 0.6-0.7...0.9-1.0区间的掩码是用stroke算法生成的，每个区间各100份，共500份

所以掩码数据总共1000份，10个比例区间，每个区间100张，每个区间的掩码都一一和100张psv数据相乘作为输入。

也就是说，
0-0.1掩码区间的100张mask和100张psv图一一相乘，得到100张0-0.1污染比例的输入图
0.1-0.2掩码区间的100张mask和100张psv图一一相乘，得到100张0.1-0.2污染比例的输入图
.....
0.9-1.0掩码区间的100张mask和100张psv图一一相乘，得到100张0.9-1.0污染比例的输入图

1000张mask都是不一样的，而100张psv图每张复用了十次。

在我的实验里，为了和其它算法比较，psv图和mask是严格一一对应的（places2和celeba也是如此），并不是随机匹配的，这样保证所有算法的输入是完全一致的。

实际反映到论文的数据，我只选取了0.1-0.3，0.3-0.5，0.5-0.7三种比例的测试结果。

**Comment by TT-mouse** [comment]
> 你好，我刚刚去翻了一下，结合我的回忆，实际上是这样的： psv原始数据集其实只提供了100张测试样本，我个人将其额外复制了9份，共1000份。 掩码数据（小）：从nvidia mask数据集中0-0.1，0.1-0.2，0.2-0.3，0.3-0.4，0.4-0.5五种掩模区间各取100份，共500份 掩码数据（大）：0.5-0.6, 0.6-0.7...0.9-1.0区间的掩码是用stroke算法生成的，每个区间各100份，共500份
> 
> 所以掩码数据总共1000份，10个比例区间，每个区间100张，每个区间的掩码都一一和100张psv数据相乘作为输入。
> 
> 也就是说， 0-0.1掩码区间的100张mask和100张psv图一一相乘，得到100张0-0.1污染比例的输入图 0.1-0.2掩码区间的100张mask和100张psv图一一相乘，得到100张0.1-0.2污染比例的输入图 ..... 0.9-1.0掩码区间的100张mask和100张psv图一一相乘，得到100张0.9-1.0污染比例的输入图
> 
> 1000张mask都是不一样的，而100张psv图每张复用了十次。
> 
> 在我的实验里，为了和其它算法比较，psv图和mask是严格一一对应的（places2和celeba也是如此），并不是随机匹配的，这样保证所有算法的输入是完全一致的。
> 
> 实际反映到论文的数据，我只选取了0.1-0.3，0.3-0.5，0.5-0.7三种比例的测试结果。



> 你好，我刚刚去翻了一下，结合我的回忆，实际上是这样的： psv原始数据集其实只提供了100张测试样本，我个人将其额外复制了9份，共1000份。 掩码数据（小）：从nvidia mask数据集中0-0.1，0.1-0.2，0.2-0.3，0.3-0.4，0.4-0.5五种掩模区间各取100份，共500份 掩码数据（大）：0.5-0.6, 0.6-0.7...0.9-1.0区间的掩码是用stroke算法生成的，每个区间各100份，共500份
> 
> 所以掩码数据总共1000份，10个比例区间，每个区间100张，每个区间的掩码都一一和100张psv数据相乘作为输入。
> 
> 也就是说， 0-0.1掩码区间的100张mask和100张psv图一一相乘，得到100张0-0.1污染比例的输入图 0.1-0.2掩码区间的100张mask和100张psv图一一相乘，得到100张0.1-0.2污染比例的输入图 ..... 0.9-1.0掩码区间的100张mask和100张psv图一一相乘，得到100张0.9-1.0污染比例的输入图
> 
> 1000张mask都是不一样的，而100张psv图每张复用了十次。
> 
> 在我的实验里，为了和其它算法比较，psv图和mask是严格一一对应的（places2和celeba也是如此），并不是随机匹配的，这样保证所有算法的输入是完全一致的。
> 
> 实际反映到论文的数据，我只选取了0.1-0.3，0.3-0.5，0.5-0.7三种比例的测试结果。

通过您详细的描述，我已经理解了论文中测试部分图片的设置了，十分感谢！
